name: CI
on: [push]
jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install
      run: npm i
    - name: Lint
      run: npm run lint
    - name: Coverage
      run: npm run coverage
    - name: Badges
      uses: jpb06/jest-badges-action@latest
      with:
        branches: main